/**
 * The photo manifest — and the shot list.
 *
 * Every `<ArtSlot brief="…">` looks itself up here by its brief. Map a brief
 * to a file in /public/photos and that slot renders a photograph instead of a
 * colour field. Set it back to null and the placeholder returns.
 *
 * Current images are generated placeholders — FLUX-1-schnell via Cloudflare
 * Workers AI, regenerated by scripts/generate-photos.mjs. Apache-2.0, so
 * commercially usable, but they are stand-ins for a real shoot: the packaging
 * is invented and will not match the finished carton.
 *
 * Sources are square. ArtSlot renders them with object-cover, so each is
 * cropped to its slot's aspect at render time — `position` nudges that crop.
 *
 * No hands, no faces, no mouths anywhere in this set — deliberately.
 * FLUX-1-schnell at eight steps reliably mangles them: fused fingers, four
 * hands where two were asked for, jewellery that was explicitly excluded.
 * Every such slot was recomposed as an object or a room instead.
 *
 * The real shoot should absolutely include them — a strip between finger and
 * thumb, hands opening the box, a strip going onto the tongue. Those are the
 * shots that sell the format. They are missing here only because the
 * generator cannot do them, not because they are wrong for the brand.
 */

export type Photo = {
  src: string;
  /** Written for a screen reader, not a caption */
  alt: string;
  /** Nudge the crop when the subject isn't centred */
  position?: string;
};

export const PHOTOS: Record<string, Photo | null> = {
  // ---- Hero ------------------------------------------------------------
  "the strips on a bedside table, low evening light": {
    src: "/photos/hero-table.jpg",
    alt: "NODA boxes on a wooden table in a bright room, garden foliage behind",
    // Weighted low so the boxes stay whole when the square source is
    // cropped to a wide hero
    position: "center 72%",
  },

  // ---- Product ---------------------------------------------------------
  "the box, straight on": {
    src: "/photos/box-front.jpg",
    alt: "A NODA box photographed straight on against deep teal",
  },
  "two boxes, straight on, bone ground": {
    src: "/photos/box-pair.jpg",
    alt: "Two NODA boxes on a warm bone surface with long soft shadows",
  },
  "the box, opened": {
    src: "/photos/box-open.jpg",
    alt: "An opened NODA box showing the strips stacked inside",
  },
  "a single strip on a pale surface": {
    src: "/photos/strip-single.jpg",
    alt: "A single translucent sleep strip resting on a pale surface",
  },
  "bedside, lamp low": {
    src: "/photos/bedside-lamp.jpg",
    alt: "A bedside corner at night lit by one low warm lamp",
  },
  "the product, deep brand": {
    src: "/photos/product-teal.jpg",
    alt: "A NODA box lit from behind on a deep teal ground",
  },

  // ---- The format ------------------------------------------------------
  "macro of the film, backlit": {
    src: "/photos/film-macro.jpg",
    alt: "Extreme close-up of the dissolvable film, backlit",
  },
  "cross-section of the strip": {
    src: "/photos/strip-section.jpg",
    alt: "A single translucent strip lit from behind on a pale surface",
  },

  // ---- Science ---------------------------------------------------------
  "illustration — the body clock, brand": {
    src: "/photos/body-clock.jpg",
    alt: "An abstract ring diagram of the daily body clock",
  },

  // ---- Member stories (mood, deliberately not portraits) ---------------
  "a bed at first light": {
    src: "/photos/bed-first-light.jpg",
    alt: "An empty made bed in soft first light",
  },
  "folded linen on a chair": {
    src: "/photos/linen-chair.jpg",
    alt: "Folded oatmeal linen on a pale wooden chair",
  },
  "a bedside lamp switched off": {
    src: "/photos/lamp-off.jpg",
    alt: "A bedside lamp just switched off in a dark room",
  },
  "curtains and early sun": {
    src: "/photos/curtains-sun.jpg",
    alt: "Early sun glowing through a linen curtain",
  },

  // ---- Mosaic ----------------------------------------------------------
  "the strip, edge on, macro": {
    src: "/photos/strip-edge.jpg",
    alt: "Extreme close-up of the strip seen edge on",
  },
  "the box, lid lifted, from above": {
    src: "/photos/box-lid.jpg",
    alt: "A NODA box from above with its lid lifted beside it",
  },
  "the box on a bedside table": {
    src: "/photos/box-table.jpg",
    alt: "A NODA box beside a glass of water in morning light",
  },
  "a strip against a bright window": {
    src: "/photos/strip-window.jpg",
    alt: "A translucent strip resting against a bright window sill",
  },
  "morning light on linen": {
    src: "/photos/linen-morning.jpg",
    alt: "Morning sunlight falling across folded linen",
  },
  "packaging detail, macro": {
    src: "/photos/packaging-macro.jpg",
    alt: "Extreme close-up of the matte teal carton edge",
  },
  "a glass of water, evening shadow": {
    src: "/photos/water-glass.jpg",
    alt: "A glass of water casting a long evening shadow",
  },
  "linen and lamplight, wide": {
    src: "/photos/linen-lamplight.jpg",
    alt: "Oatmeal linen lit by a single warm lamp out of frame",
  },


  // ---- Comparison bar fills --------------------------------------------
  "format fill — oral strip": {
    src: "/photos/fmt-strip-stack.jpg",
    alt: "Dissolvable film strips overlapping, close up",
  },
  "format fill — powder": {
    src: "/photos/fmt-powder-granules.jpg",
    alt: "A mound of fine white supplement powder",
  },
  "format fill — gummy": {
    src: "/photos/fmt-gummy-pile.jpg",
    alt: "A pile of sugar-dusted gummies",
  },
  "format fill — capsule": {
    src: "/photos/fmt-capsule-pile.jpg",
    alt: "A pile of plain off-white capsules",
  },
  "format fill — tablet": {
    src: "/photos/fmt-tablet-pile.jpg",
    alt: "A stack of plain white tablets",
  },

  // ---- Closing cards ---------------------------------------------------
  "landscape, dusk, wide": {
    src: "/photos/dusk-landscape.jpg",
    alt: "An empty landscape at dusk under a deep teal sky",
  },
};

export function getPhoto(brief: string): Photo | null {
  return PHOTOS[brief] ?? null;
}
