/**
 * The photo manifest — and the shot list.
 *
 * Every `<ArtSlot brief="…">` looks itself up here by its brief. Map a brief
 * to a file in /public/photos and that slot renders a photograph instead of a
 * colour field. Set it back to null and the placeholder returns.
 *
 * Current images are generated placeholders — FLUX-1-schnell via Cloudflare
 * Workers AI, regenerated by scripts/generate-photos.mjs. Apache-2.0, so
 * commercially usable, but they are stand-ins for a real shoot: the packaging
 * is invented and will not match the finished carton.
 *
 * Sources are square. ArtSlot renders them with object-cover, so each is
 * cropped to its slot's aspect at render time — `position` nudges that crop.
 *
 * No hands, no faces, no mouths anywhere in this set — deliberately.
 * FLUX-1-schnell at eight steps reliably mangles them: fused fingers, four
 * hands where two were asked for, jewellery that was explicitly excluded.
 * Every such slot was recomposed as an object or a room instead.
 *
 * The real shoot should absolutely include them — a strip between finger and
 * thumb, hands opening the box, a strip going onto the tongue. Those are the
 * shots that sell the format. They are missing here only because the
 * generator cannot do them, not because they are wrong for the brand.
 */

export type Photo = {
  src: string;
  /** Written for a screen reader, not a caption */
  alt: string;
  /** Nudge the crop when the subject isn't centred */
  position?: string;
};

export const PHOTOS: Record<string, Photo | null> = {
  // ---- Hero ------------------------------------------------------------
  "the strips on a bedside table, low evening light": {
    // Night, on purpose: the strip is taken half an hour before bed, and a
    // bright daylight hero was arguing against the product. One warm lamp
    // against cool dusk in the window, with the strip backlit so it glows —
    // the format is the whole argument, so it has to be the brightest thing
    // in the frame. hero-plinth.jpg is the daylight alternative.
    src: "/photos/hero-night.jpg",
    alt: "A NODA carton on a bedside table at night, a frosted strip glowing beside it",
    // Biased right, toward the product. On a wide screen the slot matches
    // the frame's aspect so this does nothing; on a phone the sides are
    // cropped hard, and centring would leave only an empty table on screen.
    position: "68% center",
  },

  // ---- Product ---------------------------------------------------------
  "the box, straight on": {
    src: "/photos/box-front.jpg",
    alt: "A NODA box photographed straight on against deep teal",
  },
  "two boxes, straight on, bone ground": {
    src: "/photos/box-pair.jpg",
    alt: "Two NODA boxes on a warm bone surface with long soft shadows",
  },
  "the box, opened": {
    src: "/photos/box-open.jpg",
    alt: "An opened NODA box showing the strips stacked inside",
  },
  "a single strip on a pale surface": {
    src: "/photos/strip-single.jpg",
    alt: "A single translucent sleep strip resting on a pale surface",
  },
  "bedside, lamp low": {
    src: "/photos/bedside-lamp.jpg",
    alt: "A bedside corner at night lit by one low warm lamp",
  },
  "the product, deep brand": {
    src: "/photos/product-teal.jpg",
    alt: "A NODA box lit from behind on a deep teal ground",
  },

  // ---- The format ------------------------------------------------------
  "macro of the film, backlit": {
    src: "/photos/film-macro.jpg",
    alt: "Extreme close-up of the dissolvable film, backlit",
  },
  "cross-section of the strip": {
    src: "/photos/strip-section.jpg",
    alt: "A single translucent strip lit from behind on a pale surface",
  },

  // ---- Science ---------------------------------------------------------
  "illustration — the body clock, brand": {
    src: "/photos/body-clock.jpg",
    alt: "An abstract ring diagram of the daily body clock",
  },

  // ---- Member stories (mood, deliberately not portraits) ---------------
  "a bed at first light": {
    src: "/photos/bed-first-light.jpg",
    alt: "An empty made bed in soft first light",
  },
  "folded linen on a chair": {
    src: "/photos/linen-chair.jpg",
    alt: "Folded oatmeal linen on a pale wooden chair",
  },
  "a bedside lamp switched off": {
    src: "/photos/lamp-off.jpg",
    alt: "A bedside lamp just switched off in a dark room",
  },
  "curtains and early sun": {
    src: "/photos/curtains-sun.jpg",
    alt: "Early sun glowing through a linen curtain",
  },

  // ---- Mosaic ----------------------------------------------------------
  "the strip, edge on, macro": {
    src: "/photos/strip-edge.jpg",
    alt: "Extreme close-up of the strip seen edge on",
  },
  "the box, lid lifted, from above": {
    src: "/photos/box-lid.jpg",
    alt: "A NODA box from above with its lid lifted beside it",
  },
  "the box on a bedside table": {
    src: "/photos/box-table.jpg",
    alt: "A NODA box beside a glass of water in morning light",
  },
  "a strip against a bright window": {
    src: "/photos/strip-window.jpg",
    alt: "A translucent strip resting against a bright window sill",
  },
  "morning light on linen": {
    src: "/photos/linen-morning.jpg",
    alt: "Morning sunlight falling across folded linen",
  },
  "packaging detail, macro": {
    src: "/photos/packaging-macro.jpg",
    alt: "Extreme close-up of the matte teal carton edge",
  },
  "a glass of water, evening shadow": {
    src: "/photos/water-glass.jpg",
    alt: "A glass of water casting a long evening shadow",
  },
  "linen and lamplight, wide": {
    src: "/photos/linen-lamplight.jpg",
    alt: "Oatmeal linen lit by a single warm lamp out of frame",
  },


  // ---- Ingredient cards: the ingredient itself, as the reference does --
  "ingredient — tart cherry": {
    src: "/photos/ing-melatonin.jpg",
    alt: "Fresh tart cherries on a pale surface",
  },
  "ingredient — green tea leaf": {
    src: "/photos/ing-theanine.jpg",
    alt: "Fresh green tea leaves on a pale surface",
  },
  "ingredient — magnesium mineral": {
    src: "/photos/ing-magnesium.jpg",
    alt: "Pale mineral crystals on a pale surface",
  },
  "ingredient — lemon balm": {
    src: "/photos/ing-lemonbalm.jpg",
    alt: "Sprigs of fresh lemon balm on a pale surface",
  },
  "ingredient — the film": {
    src: "/photos/ing-film.jpg",
    alt: "Two translucent dissolvable film squares on a pale surface",
  },

  // ---- Comparison bar fills --------------------------------------------
  "format fill — oral strip": {
    src: "/photos/fmt-strip-stack.jpg",
    alt: "Dissolvable film strips overlapping, close up",
  },
  "format fill — powder": {
    src: "/photos/Powder.png",
    alt: "A steep mountain of fine white supplement powder, raked by low light",
  },
  "format fill — gummy": {
    src: "/photos/gummies.png",
    alt: "A pile of sugar-dusted gummies",
  },
  "format fill — capsule": {
    src: "/photos/Capsules.png",
    alt: "A pile of plain off-white capsules",
  },
  "format fill — tablet": {
    src: "/photos/Tablets.png",
    alt: "A stack of plain white tablets",
  },

  // ---- Closing cards ---------------------------------------------------
  "landscape, dusk, wide": {
    src: "/photos/dusk-landscape.jpg",
    alt: "An empty landscape at dusk under a deep teal sky",
  },
};

export function getPhoto(brief: string): Photo | null {
  return PHOTOS[brief] ?? null;
}
